# Change these first
owner: akuraito
repo: upptime

sites:
  - name: AVATAR_PROXY
    url: $AVATAR_PROXY
  - name: BITWARDEN
    url: $BITWARDEN
  - name: BLOG
    url: $BLOG
  - name: BROADCASTCHANNEL
    url: $BROADCASTCHANNEL
  - name: DC1
    url: $DC1
  - name: HEIMDALLR
    url: $HEIMDALLR
  - name: WALINE
    url: $WALINE

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: speedtest.akurai.to
  # baseUrl: /your-repo-name
  logoUrl: https://akurai.to/images/favicon.svg
  name: エラー はっせい
  introTitle: ""
  introMessage: 
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: 😎
      href: https://akurai.to

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
